### ISSUE TITLE
Download warpx.jar

### ISSUE THREAD

**Issue by SrBedrock** [ReflxctionDev/WarpsX#1] opened 2019-12-04 03:41 UTC
I can't compile with intellij, would there be any way for you to make .jar available?

**Comment by Revxrsal** [comment] 2019-12-04 04:15
> I can't compile with intellij, would there be any way for you to make .jar available?

Sorry, the problem is one of the dependencies. I'll fix it when I get home.

**Comment by SrBedrock** [comment] 2019-12-04 04:16
[No problem, I found the spigot link.](https://www.spigotmc.org/resources/warpsx-a-powerful-feature-rich-warps-plugin.73006/)

**Comment by Revxrsal** [comment] 2019-12-05 15:18
The dependencies should work fine now. Closing this issue

**Closed as completed by Revxrsal** 2019-12-05 15:18 UTC
